fix(Travel/delete): fix route and models
ASVVlasov/Travel_Planner pull request #107
Opened 2020-05-29 19:37 UTC by Konstantin-Buzuev

2020-05-29 19:37 UTC, Konstantin-Buzuev commented
![](https://github.trello.services/images/mini-trello-icon.png) [Travel / логика удаления #BE29](https://trello.com/c/Qud2AVEn/149-travel-%D0%BB%D0%BE%D0%B3%D0%B8%D0%BA%D0%B0-%D1%83%D0%B4%D0%B0%D0%BB%D0%B5%D0%BD%D0%B8%D1%8F-be29)

2020-06-01 16:08 UTC, ASVVlasov requested changes

2020-06-01 16:08 UTC, ASVVlasov commented on backend/src/models/card.js
>        await this.findOneAndRemove({ _id: card.id })
у нас в findOneAndRemove есть уже удаление файлов и плательщиков

2020-06-01 16:08 UTC, ASVVlasov commented on backend/src/models/card.js
> +         let update = { $pull: { cards: card._id } }
тут findByIdAndRemove и не надо дополнительно файлы вручную удалять

2020-06-01 16:08 UTC, ASVVlasov commented on backend/src/models/payer.js
> +      await this.findOneAndDelete({ user, cardId })
не используй Delete на него нет хуков

2020-06-02 19:18 UTC, ASVVlasov submitted a review, later dismissed

2020-06-02 19:19 UTC, ASVVlasov approved these changes

2020-06-02 19:19 UTC, merged