Feature/FE35
ASVVlasov/Travel_Planner pull request #111
Opened 2020-05-31 18:17 UTC by LenaMaltseva

2020-05-31 18:17 UTC, LenaMaltseva commented
![](https://github.trello.services/images/mini-trello-icon.png) [User Page / Contacts #FE35](https://trello.com/c/I2u4mHC8/36-user-page-contacts-fe35)

2020-06-02 11:02 UTC, ASVVlasov requested changes

2020-06-02 11:02 UTC, ASVVlasov commented on frontend/src/components/Forms/ContactForm.jsx
> +   }
переделай без innerHTML(например через state) а в верстке уже брать этот стейт и отрисовывать

2020-06-02 11:02 UTC, ASVVlasov commented on frontend/src/controls/Input/BaseInputControl.jsx
> +      if (this.props.onKeyUp) this.props.onKeyUp(evt)
{} пропустила

2020-06-02 11:02 UTC, ASVVlasov commented on frontend/src/controls/Input/InputControl.jsx
> +      if (this.props.onKeyUp) this.props.onKeyUp(evt)
тоже {}

2020-06-02 11:05 UTC, LenaMaltseva commented on frontend/src/components/Forms/ContactForm.jsx
> +   }
Не получается - кнопок может быть много, а стейт - один..

2020-06-02 12:49 UTC, ASVVlasov approved these changes

2020-06-02 12:49 UTC, merged