Backend/Bugs #BE32
ASVVlasov/Travel_Planner pull request #118
Opened 2020-06-05 16:36 UTC by Konstantin-Buzuev

2020-06-05 17:26 UTC, Konstantin-Buzuev commented
![](https://github.trello.services/images/mini-trello-icon.png) [Backend / bugs #BE32](https://trello.com/c/mSEaJ0OB/154-backend-bugs-be32)

2020-06-06 16:35 UTC, ASVVlasov requested changes

2020-06-06 16:35 UTC, ASVVlasov commented on backend/src/models/travel.js
> +   let today = Date.now()
const

2020-06-06 16:35 UTC, ASVVlasov commented on backend/src/models/travel.js
> +}
а ты проверял это все работает? next вынеси из условий в конец, функцию желательно вынести куда нибудь чтобы тут не было объявления функции

2020-06-06 16:47 UTC, Konstantin-Buzuev commented on backend/src/models/travel.js
> +   let today = Date.now()
Исправил

2020-06-06 16:48 UTC, Konstantin-Buzuev commented on backend/src/models/travel.js
> +}
next() исправил. Проверял вчера - все работает. Эта функция воспринимается как мидлвара. Сделать ее методом модели? Просто выносить в качестве отдельной мидлвары как-то душа не лежит.

2020-06-06 17:51 UTC, ASVVlasov approved these changes

2020-06-07 20:15 UTC, ASVVlasov approved these changes

2020-06-07 20:15 UTC, merged