Feature/FE6
ASVVlasov/Travel_Planner pull request #12
Opened 2020-04-26 15:57 UTC by LenaMaltseva

2020-04-27 23:01 UTC, ASVVlasov requested changes

2020-04-27 23:01 UTC, ASVVlasov commented on frontend/src/components/Board/Board.jsx
> +      })
раздели логику рендера и parsePropsToState, т.е. даже название напрашивает тут просто парсить объект в стейт а в рендере его уже на верстку пускать + я бы оптимизировал forEach + push через map

2020-04-28 01:18 UTC, LenaMaltseva commented on frontend/src/components/Board/Board.jsx
> +      })
Спасибо, поправила)

2020-04-28 09:26 UTC, LenaMaltseva commented on frontend/src/components/Board/Board.module.scss
> +   height: calc(100vh - 175px);
Тестово собрала TravelPage: получается, что пока оттуда не "наследуется" высота для моего компонента. Задала ее в своих стилях, но надо по идее разобраться с этим на странице и убрать из этого компонента

2020-04-28 09:42 UTC, ASVVlasov approved these changes
good job!

2020-04-28 09:47 UTC, merged

2020-04-29 14:13 UTC, LenaMaltseva commented
![](https://github.trello.services/images/mini-trello-icon.png) [Travel Page / board #FE6](https://trello.com/c/rFGrH4SZ/45-travel-page-board-fe6)