Feature/FE47
ASVVlasov/Travel_Planner pull request #126
Opened 2020-06-09 22:45 UTC by LenaMaltseva

2020-06-09 22:45 UTC, LenaMaltseva commented
![](https://github.trello.services/images/mini-trello-icon.png) [Заверстать компонент с сообщениями error\warning\success #FE47](https://trello.com/c/qRXzswoB/162-%D0%B7%D0%B0%D0%B2%D0%B5%D1%80%D1%81%D1%82%D0%B0%D1%82%D1%8C-%D0%BA%D0%BE%D0%BC%D0%BF%D0%BE%D0%BD%D0%B5%D0%BD%D1%82-%D1%81-%D1%81%D0%BE%D0%BE%D0%B1%D1%89%D0%B5%D0%BD%D0%B8%D1%8F%D0%BC%D0%B8-error-warning-success-fe47)

2020-06-10 17:25 UTC, ASVVlasov requested changes

2020-06-10 17:25 UTC, ASVVlasov commented on frontend/src/controls/Alert/Alert.module.scss
> +   }
сделай миксин куда будешь передавать текст)

2020-06-10 17:25 UTC, ASVVlasov commented on frontend/src/controls/Alert/Alert.jsx
> +      requestForRepeat: PropTypes.func,
isRequired

2020-06-10 17:54 UTC, LenaMaltseva commented on frontend/src/controls/Alert/Alert.module.scss
> +   }
Текст? Сделала с передачей цветов..

2020-06-10 17:54 UTC, LenaMaltseva commented on frontend/src/controls/Alert/Alert.jsx
> +      requestForRepeat: PropTypes.func,
Изначально обязателен только тип, поправила

2020-06-10 19:06 UTC, ASVVlasov approved these changes

2020-06-10 19:06 UTC, merged