feat(controllers): add traveler controller
ASVVlasov/Travel_Planner pull request #13
Opened 2020-04-27 10:24 UTC by Konstantin-Buzuev

Пока добавляю основной функционал, без добавления контактов, персональной информации и профиля.
По задаче: пока делаю только CRUD. Дополнительные опции, например, выдача фронту личного кабинета пользователя и т.п. - в отдельной таске(думаю поместить во view).

2020-04-27 11:06 UTC, rri9 commented on backend/src/controllers/traveler.js
> +        const newTraveler = await Traveler.create({
Я думаю нужна проверка на уникальность логина

2020-04-27 11:06 UTC, rri9 commented on backend/src/controllers/traveler.js
> +        res.json(newTraveler._id);
res.json({ id: newTraveler._id})  ?

2020-04-27 11:06 UTC, rri9 commented on backend/src/controllers/traveler.js
> +        res.json(newTraveler._id);
Я бы унифицировал ответ сервера: всегда отправлять объект с полем status,  в том числе при успешном запросе

2020-04-27 11:06 UTC, rri9 commented on backend/src/controllers/traveler.js
> +        const newTraveler = await Traveler.create({
Пароль храним в открытом виде?

2020-04-27 18:22 UTC, Konstantin-Buzuev commented
Req: Я думаю нужна проверка на уникальность логина/
Res: Проверку на уникальность пары логин/пароль (меня всегда парило, почему на сервере не может быть двух Константинов, например, поэтому именно пары) буду вводит в следующих спринтах, когда будем пилить токен.
 
Req: res.json({ id: newTraveler._id}) ?
Res:Ага. Поправлю, спасибо. Может ввобще буду newTraveler возвращать.
 
Req: Я бы унифицировал ответ сервера: всегда отправлять объект с полем status, в том числе при успешном запросе.
Res: При успешном будет statusCode = 200, а вот при неудаче добавляю статус, поясняющий причину «косяка». В идеале эти ветки вообще не должны срабатывать.
 
Req: Пароль храним в открытом виде?
Res: До введения токенов — да.
 
Res.status(200).json({result: «Спасибо за комменты!»})
  
>Понедельник, 27 апреля 2020, 15:06 +04:00 от rri9 <notifications@github.com>:
> 
> 
>@rri9 commented on this pull request.
>----------------------------------------------------------------------
>In  backend/src/controllers/traveler.js :
>> @@ -0,0 +1,112 @@
>
>+const Traveler = require("../models/traveler.js");
>
>+
>
>+const create = async (req, res) => {
>
>+    const {
>
>+        login,
>
>+        password,
>
>+        mail
>
>+    } = req.body;
>
>+
>
>+    try {
>
>+        const newTraveler = await Traveler.create({
>
>
>Я думаю нужна проверка на уникальность логина
>----------------------------------------------------------------------
>In  backend/src/controllers/traveler.js :
>> +const Traveler = require("../models/traveler.js");
>
>+
>
>+const create = async (req, res) => {
>
>+    const {
>
>+        login,
>
>+        password,
>
>+        mail
>
>+    } = req.body;
>
>+
>
>+    try {
>
>+        const newTraveler = await Traveler.create({
>
>+            login: login,
>
>+            password: password,
>
>+            mail: mail,
>
>+        });
>
>+        res.json(newTraveler._id);
>
>
>res.json({ id: newTraveler._id}) ?
>----------------------------------------------------------------------
>In  backend/src/controllers/traveler.js :
>> +const Traveler = require("../models/traveler.js");
>
>+
>
>+const create = async (req, res) => {
>
>+    const {
>
>+        login,
>
>+        password,
>
>+        mail
>
>+    } = req.body;
>
>+
>
>+    try {
>
>+        const newTraveler = await Traveler.create({
>
>+            login: login,
>
>+            password: password,
>
>+            mail: mail,
>
>+        });
>
>+        res.json(newTraveler._id);
>
>
>Я бы унифицировал ответ сервера: всегда отправлять объект с полем status, в том числе при успешном запросе
>----------------------------------------------------------------------
>In  backend/src/controllers/traveler.js :
>> @@ -0,0 +1,112 @@
>
>+const Traveler = require("../models/traveler.js");
>
>+
>
>+const create = async (req, res) => {
>
>+    const {
>
>+        login,
>
>+        password,
>
>+        mail
>
>+    } = req.body;
>
>+
>
>+    try {
>
>+        const newTraveler = await Traveler.create({
>
>
>Пароль храним в открытом виде?
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
--
Константин Бузуев
 

2020-04-30 18:29 UTC, ASVVlasov requested changes
Поправь все, также я бы создал какой нибудь объект для ошибок чтобы его отдавать чтобы при каждом неудачном выполнении не текстом писать а ошибки в одно место засунуть
лучше вынести  create delete и т.д. в отдельные контроллеры, да будет много контроллеров но в каждом будет своя логика и он будет небольшим

2020-04-30 18:29 UTC, ASVVlasov commented on backend/src/controllers/accomodation.js
> +        });
1. зачем деструктурировать body если ты его же пихаешь в конструктор Accomodation, когда можно просто new Accomodation(req.body) предварительно в body засунув travelers
2. travalers !== undefined -> !travelers
3. во всех конструкциях if, даже если там один оператор, используй {}

2020-04-30 18:29 UTC, ASVVlasov commented on backend/src/controllers/accomodation.js
> +        })
если у нас не найдет id то ты отдашь фронту ошибку но выше сработает new Accomodation, перенеси эти проверки вверх

2020-04-30 18:29 UTC, ASVVlasov commented on backend/src/controllers/accomodation.js
> +    }
if (!id) и я бы назвал все таки cardId

2020-04-30 18:29 UTC, ASVVlasov commented on backend/src/controllers/accomodation.js
> +    }
тоже что и выше

2020-04-30 18:29 UTC, ASVVlasov commented on backend/src/controllers/accomodation.js
> +        return
тут и дальше везде поправь что выше я уже писал

2020-04-30 18:29 UTC, ASVVlasov commented on backend/src/controllers/accomodation.js
> +            req.body.travelers.length !== 0) accomodation.travelers = req.body.travelers;
опять же !req.body.field_name, а лучше решение это 
Object.keys(req.body).foreach((key) => {
accomodation[key] = req.body[key]
})

2020-05-01 12:57 UTC, Konstantin-Buzuev commented
![](https://github.trello.services/images/mini-trello-icon.png) [CRUD для traveler, board, card #BE4](https://trello.com/c/jq1Mbznp/49-crud-%D0%B4%D0%BB%D1%8F-traveler-board-card-be4)

2020-05-01 20:54 UTC, ASVVlasov submitted a review, later dismissed
в целом выглядит уже неплохо, дальше вылезет уже) если что не так

2020-05-01 20:54 UTC, ASVVlasov commented on backend/src/controllers/card/read.js
> +    }
тут и в других контроллерах в этом же месте вроде у тебя ошибочка)

2020-05-02 10:39 UTC, ASVVlasov requested changes

2020-05-02 10:39 UTC, ASVVlasov commented on backend/src/controllers/card/attachment.js
> +        })
if () {}

2020-05-02 10:39 UTC, ASVVlasov commented on backend/src/controllers/card/attachment.js
> +        })
опять же {} в конструкции if

2020-05-02 11:21 UTC, ASVVlasov submitted a review, later dismissed

2020-05-02 11:23 UTC, merged