feature/FE51
ASVVlasov/Travel_Planner pull request #133
Opened 2020-06-11 18:22 UTC by ASVVlasov

2020-06-11 18:27 UTC, LenaMaltseva reviewed
по отступу -ок

2020-06-11 20:41 UTC, LenaMaltseva requested changes
Понимаю, что об этом не написано в задаче, но у нас title\alt для аватарок и span с именем юзера тоже косячные - сейчас там только никнеймы. Поправь тоже, пожалуйста.

2020-06-11 20:41 UTC, LenaMaltseva commented on frontend/src/components/Cards/CardFull.jsx
> +                     />
здесь и везде ниже: в title и alt нужно добавить логику как в отображении имени, т.е. там должны быть фамилия и имя, а если они не заданы, то ник юзера

2020-06-11 20:41 UTC, LenaMaltseva commented on frontend/src/components/Cards/CardFull.jsx
> +                        : payer.user.nickName
можно подсократить с учетом деструктуризации выше

2020-06-11 20:41 UTC, LenaMaltseva commented on frontend/src/components/Cards/CardShort.jsx
> +         ).toUpperCase()
upperCase, кстати, можно больше не делать, в css настроен text-transform :)

2020-06-11 20:41 UTC, LenaMaltseva commented on frontend/src/controls/UserPicker/UserPicker.jsx
> +               {this.usersRender(allUsers, chosenUsers)}
эм, в данном компоненте не понимаю в чем рефакторинг - глобально рендер состоял из одного мэпа, а сейчас это два(?) мэпа вне его, зачем?

2020-06-11 20:41 UTC, LenaMaltseva commented on frontend/src/controls/UserPicker/UserPicker.jsx
> +            <div className={styles.user} key={user._id}>
если уж отрефакторено) то можно:
```
usersRender = (users, chosenUsers) => 
    users.map((user) => (
        <div className={styles.user} key={user._id}>...</div>
    ))
```

2020-06-11 20:41 UTC, LenaMaltseva commented on frontend/src/components/Cards/CardFull.jsx
> +                                    unexpiredCard &&
стяни дев, это уже было в 50й ветке)

2020-06-11 21:54 UTC, ASVVlasov commented
![](https://github.trello.services/images/mini-trello-icon.png) [баги на фронте #FE51](https://trello.com/c/PRVh4Xwn/168-%D0%B1%D0%B0%D0%B3%D0%B8-%D0%BD%D0%B0-%D1%84%D1%80%D0%BE%D0%BD%D1%82%D0%B5-fe51)

2020-06-12 08:05 UTC, LenaMaltseva approved these changes

2020-06-12 08:06 UTC, merged