hotfix/be19: fix to be32/backend bugs
ASVVlasov/Travel_Planner pull request #135
Opened 2020-06-12 15:03 UTC by Konstantin-Buzuev

2020-06-12 15:47 UTC, Konstantin-Buzuev commented
![](https://github.trello.services/images/mini-trello-icon.png) [Backend / bugs #BE32](https://trello.com/c/mSEaJ0OB/154-backend-bugs-be32)

2020-06-15 06:46 UTC, ASVVlasov requested changes

2020-06-15 06:46 UTC, ASVVlasov commented on backend/src/models/handlers/statusHandler.js
> +   if (doc.status != travelStatuses.ARCHIVE && Date.parse(doc.endDate) < today) {
!==

2020-06-15 06:46 UTC, ASVVlasov commented on backend/src/routes/travel/index.js
> +      console.log('deleting travel')
убери это и ниже еще есть консоль

2020-06-16 16:24 UTC, ASVVlasov approved these changes

2020-06-16 16:24 UTC, merged