feature/be34
ASVVlasov/Travel_Planner pull request #139
Opened 2020-06-15 13:01 UTC by ASVVlasov

2020-06-15 13:01 UTC, ASVVlasov commented
![](https://github.trello.services/images/mini-trello-icon.png) [Обработка ошибок и выдача на фронт человеческим языком) #BE34](https://trello.com/c/KEcWP6zo/99-%D0%BE%D0%B1%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%BA%D0%B0-%D0%BE%D1%88%D0%B8%D0%B1%D0%BE%D0%BA-%D0%B8-%D0%B2%D1%8B%D0%B4%D0%B0%D1%87%D0%B0-%D0%BD%D0%B0-%D1%84%D1%80%D0%BE%D0%BD%D1%82-%D1%87%D0%B5%D0%BB%D0%BE%D0%B2%D0%B5%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D0%BC-%D1%8F%D0%B7%D1%8B%D0%BA%D0%BE%D0%BC-be34)

2020-06-15 20:38 UTC, Konstantin-Buzuev commented on backend/src/middlewares/passport.js
> +            return done(Errors.authError.passwordWrongError, false) // error, not auth
!user второй раз лишнее

2020-06-15 20:40 UTC, Konstantin-Buzuev commented on backend/src/middlewares/token.js
>     if (user && user.comparePassword(password)) {
После этого условия по хорошему нужно кидать authError.passwordWrongError, аналогично паспорту.

2020-06-15 20:43 UTC, Konstantin-Buzuev commented on backend/src/models/card.js
> +      throw Errors.cardError.notFoundError
Тут же не карточка не найдена, а тип карточки кривой пришел?

2020-06-15 20:47 UTC, Konstantin-Buzuev commented on backend/src/models/card.js
> +}
Поскольку карточка уже найдена, то лучше заменить на card.payers.push / card.save

2020-06-15 20:54 UTC, Konstantin-Buzuev commented on backend/src/models/handlers/commonHandlers.js
> +   if (!prevDate || nextDate) {
По моему, тут опечатка и должно быть !nextDate

2020-06-15 20:57 UTC, Konstantin-Buzuev commented on backend/src/models/handlers/errorHandler.js
> +      ErrorHandler(error, doc, next)
Лучше избежать дублирования кода.

2020-06-15 21:01 UTC, Konstantin-Buzuev commented on backend/src/models/handlers/statusHandler.js
>  }
Этот код был полностью переделан в hotfix/be19. Во избежание конфликтов при мердже лучше откатить эти изменения

2020-06-15 21:14 UTC, Konstantin-Buzuev commented on backend/src/routes/travel/index.js
> +      res.json(await TravelModel.updateTravel(travelModel))
Если убрать удаление свойств cards, users, то этот роут по сути будет отвечать за изменения всех сущностей в путешествии. Остальные роуты (travel/user, card/index:POST) получается не нужны. Лучше здесь вызвать метод проверки дат для карточек, но не включать их(как и user) в update. Для этого свои роуты есть.

2020-06-15 21:19 UTC, Konstantin-Buzuev commented on backend/src/routes/user/contact.js
>        }
Вынеси в models/types/errors

2020-06-15 21:20 UTC, Konstantin-Buzuev requested changes
В комментах отписался.

2020-06-16 13:39 UTC, ASVVlasov commented on backend/src/models/card.js
> +      throw Errors.cardError.notFoundError
у нас нет ошибки с кривым типом карточки а на фронт я должен отдать 404 чтобы он отобразил страницу 404

2020-06-16 13:40 UTC, ASVVlasov commented on backend/src/models/handlers/commonHandlers.js
> +   if (!prevDate || nextDate) {
все верно)

2020-06-16 15:40 UTC, ASVVlasov commented on backend/src/middlewares/token.js
>     if (user && user.comparePassword(password)) {
каким образом ты это собрался делать? и в чем смысл?

2020-06-16 15:43 UTC, ASVVlasov commented on backend/src/models/card.js
> +}
нет не лучше ибо у нас тут развернутая карточка где payers это не массив айдишников, если полностью пейера запихнуть в массив не пробовал

2020-06-16 15:46 UTC, ASVVlasov commented on backend/src/models/handlers/statusHandler.js
>  }
я не знаю что переделывалось, конфликты решаются поэтому норм

2020-06-16 15:47 UTC, Konstantin-Buzuev commented on backend/src/middlewares/token.js
>     if (user && user.comparePassword(password)) {
После 16 строки:
else throw.Errors.authError.passwordWrongError

2020-06-16 15:49 UTC, Konstantin-Buzuev commented on backend/src/models/card.js
> +}
Работает, т.к. есть хук на save

2020-06-16 15:51 UTC, Konstantin-Buzuev commented on backend/src/models/handlers/statusHandler.js
>  }
"я не знаю что переделывалось". Ты же этот код ревьюил?

2020-06-16 16:38 UTC, Konstantin-Buzuev submitted a review, later dismissed

2020-06-16 16:52 UTC, Konstantin-Buzuev approved these changes

2020-06-16 16:53 UTC, merged