Feature/be36: change travel leave/delete logic
ASVVlasov/Travel_Planner pull request #140
Opened 2020-06-15 14:58 UTC by Konstantin-Buzuev

2020-06-15 14:59 UTC, Konstantin-Buzuev commented
![](https://github.trello.services/images/mini-trello-icon.png) [Поменять логику удаления путешествия и участников #BE36](https://trello.com/c/aHgynUY7/164-%D0%BF%D0%BE%D0%BC%D0%B5%D0%BD%D1%8F%D1%82%D1%8C-%D0%BB%D0%BE%D0%B3%D0%B8%D0%BA%D1%83-%D1%83%D0%B4%D0%B0%D0%BB%D0%B5%D0%BD%D0%B8%D1%8F-%D0%BF%D1%83%D1%82%D0%B5%D1%88%D0%B5%D1%81%D1%82%D0%B2%D0%B8%D1%8F-%D0%B8-%D1%83%D1%87%D0%B0%D1%81%D1%82%D0%BD%D0%B8%D0%BA%D0%BE%D0%B2-be36)

2020-06-16 16:22 UTC, ASVVlasov requested changes

2020-06-16 16:22 UTC, ASVVlasov commented on backend/src/routes/travel/index.js
> +      if ((await TravelModel.isOwner(travelId, _id)) === true) {
вы что блин издеваетесь? сколько раз нужно писать про такие моменты, почему нельзя просто написать if (await TravelModel.isOwner(travelId, _id)) ?

2020-06-16 16:22 UTC, ASVVlasov commented on backend/src/routes/travel/index.js
> +      if ((await TravelModel.isOwner(travelId, _id)) === true) {
и эту проверку можно сделать внутри deleteTravel чтобы два раза не дергать один и тот же тревел

2020-06-17 19:15 UTC, ASVVlasov submitted a review, later dismissed

2020-06-17 19:32 UTC, ASVVlasov approved these changes

2020-06-17 19:37 UTC, merged