feature/be35
ASVVlasov/Travel_Planner pull request #149
Opened 2020-06-19 08:36 UTC by ASVVlasov

2020-06-19 09:06 UTC, ASVVlasov commented
![](https://github.trello.services/images/mini-trello-icon.png) [Приглашение по почте и рега из письма #BE35](https://trello.com/c/LgV8aZg7/180-%D0%BF%D1%80%D0%B8%D0%B3%D0%BB%D0%B0%D1%88%D0%B5%D0%BD%D0%B8%D0%B5-%D0%BF%D0%BE-%D0%BF%D0%BE%D1%87%D1%82%D0%B5-%D0%B8-%D1%80%D0%B5%D0%B3%D0%B0-%D0%B8%D0%B7-%D0%BF%D0%B8%D1%81%D1%8C%D0%BC%D0%B0-be35)

2020-06-19 16:03 UTC, Konstantin-Buzuev commented on backend/src/models/registration.js
> +}
Закинь эту функцию в хук pre('find') чтобы чистилась база

2020-06-19 16:27 UTC, Konstantin-Buzuev commented on backend/src/models/registration.js
> +   },
Замени на email, все равно больше сюда ничего не прокидывается

2020-06-19 16:28 UTC, Konstantin-Buzuev commented on backend/src/models/user.js
> +userSchema.statics.invite = async function (email) {
Этот метод нужно перенести в registration model

2020-06-19 16:30 UTC, Konstantin-Buzuev commented on backend/src/routes/auth/signup.js
> +         const invite = await RegistrationModel.findById(req.params.linkId)
замени на findByIdAndDelete, все равно дальше удаляешь эту запись.

2020-06-19 17:06 UTC, Konstantin-Buzuev commented on backend/src/routes/auth/signup.js
> +         await RegistrationModel.findByIdAndDelete(invite.id)
А тут заменить на UserModel.create и тогда будет перемещение заявки из коллекции "потенциально зарегистрируются" в "зарегистрированные пользователи"

2020-06-19 17:09 UTC, Konstantin-Buzuev commented on backend/src/models/user.js
> +   const registrationModel = await RegistrationModel.create(regUserInfo)
Не нужно создаваемого пользователя еще запихивать к тем, кто "потенциально зарегистрируется".

2020-06-19 17:11 UTC, Konstantin-Buzuev commented on backend/src/models/user.js
> +   if (this.isModified('password') && this.password !== '') {
Если разнести тех кто еще не зарегистрировался и тех кто уже зарегистрировался, то это лишнее

2020-06-19 17:14 UTC, Konstantin-Buzuev commented on backend/src/routes/user/contact.js
> +         res.json(await UserModel.invite(email))
При разнесении коллекций изменится модель

2020-06-19 17:18 UTC, Konstantin-Buzuev requested changes
В текущей реализации пользователи дублируются в registration и user модели и возникают "мертвые души" из тех кто получил, но не воспользовался регистрацией.
Предлагаю разнести эти коллекции на registration (название оставил прежним чтобы не вносить путаницу) - тех кто получил приглашение и user - тех кто воспользовался им или самостоятельно зарегистрировался.

2020-06-21 16:19 UTC, Konstantin-Buzuev submitted a review, later dismissed

2020-07-06 15:13 UTC, merged