Feature/fe58
ASVVlasov/Travel_Planner pull request #151
Opened 2020-06-21 11:30 UTC by Konstantin-Buzuev

Пока сделал только саму модалку, без подцепления. Тестил заменой UserForm в UserHeader

2020-06-21 11:31 UTC, Konstantin-Buzuev commented
![](https://github.trello.services/images/mini-trello-icon.png) [Обратная связь #FE58](https://trello.com/c/sD8fhwHF/177-%D0%BE%D0%B1%D1%80%D0%B0%D1%82%D0%BD%D0%B0%D1%8F-%D1%81%D0%B2%D1%8F%D0%B7%D1%8C-fe58)

2020-06-30 18:54 UTC, LenaMaltseva submitted a review, later dismissed
мои комменты по части соответствия макету + по изменениям в редаксе:

2020-06-30 18:54 UTC, LenaMaltseva commented on frontend/src/components/Footer/Footer.jsx
> +            >
Состояние 'hide' можно описывать в родительском классе, а не создавать для этого отдельный.
Плюс, используя библиотеку classNames, можно сократить эту часть до:
```
className={classNames(
                  styles.footer__feedback,
                  this.state.feedbackHintShown && styles.footer__feedback_show
               )}
```

2020-06-30 18:54 UTC, LenaMaltseva commented on frontend/src/components/Footer/Footer.jsx
> +               <span className={styles.footer__text}>по функционалу</span>
вместо 4 спанов с одинаковым классом, можно все объединить, например, в параграф, а внутри него к спану-ссылке обратиться через селектор пробела, получится компактнее.
```
<p className={styles.footer__text}>
    Здесь будет подробный расчет бюджета
    <br />
    Самое время&nbsp;
    <span onClick={this.openModal}>отправить пожелания</span>
    <br />
    по функционалу
</p>
```

2020-06-30 18:54 UTC, LenaMaltseva commented on frontend/src/components/Footer/footer.module.scss
> +    &__switch {
зачем это добавлять? :)

2020-06-30 18:54 UTC, LenaMaltseva commented on frontend/src/components/Footer/footer.module.scss
> +        }
"opacity: 0" есть в элементе __feedback, туда же можно перенести "visibility: hidden"\"display: none", а в модификатор _show добавить обратное состояние

2020-06-30 18:54 UTC, LenaMaltseva commented on frontend/src/components/Footer/footer.module.scss
> +        box-shadow: 2px 2px 10px rgba(145, 174, 212, 0.2);
@include BaseShadow

2020-06-30 18:54 UTC, LenaMaltseva commented on frontend/src/components/Footer/footer.module.scss
> +        right: 0px;
bottom: 90px;
right: 40px;

2020-06-30 18:54 UTC, LenaMaltseva commented on frontend/src/components/Footer/footer.module.scss
> +        @include Subtitle-1-Regular;
тут давай поменяем на Text-Regular, а то слишком крупно выходит

2020-06-30 18:54 UTC, LenaMaltseva commented on frontend/src/components/Footer/footer.module.scss
>          @include IconBright(40px);
IconLight должно быть по макету

2020-06-30 18:54 UTC, LenaMaltseva commented on frontend/src/components/Forms/FeedbackForm.module.scss
> +        margin-bottom: 30px;
уменьшить до 24рх

2020-06-30 18:54 UTC, LenaMaltseva commented on frontend/src/redux/feedback/actions.js
> +   payload: { regError: err.message },
причем тут regError?

2020-06-30 18:54 UTC, LenaMaltseva commented on frontend/src/redux/feedback/operations.js
> +   fetchRequest.post('/feedback', [feedbackSuccess, feedbackError], comment)
в массив первым экшеном передается экшн загрузки (loading) либо null
стяни дев (после задачи по обработке событий и состояний приложения структура функции fetchData поменялась) и сделай по аналогии

2020-06-30 18:54 UTC, LenaMaltseva commented on frontend/src/redux/fetch/operations.js
> -
зачем?

2020-06-30 18:54 UTC, LenaMaltseva commented on frontend/src/components/Footer/UserFooter.jsx
> +               <span className={styles.footer__link}>Поддержать проект</span>
у нас еще нет этого функционала, соот-но пока надо убрать

2020-06-30 18:54 UTC, LenaMaltseva commented on frontend/src/components/Footer/UserFooter.jsx
> +            </div>
поправь стили - на вкладке "контакты" блок со ссылками "уезжают" налево, а должен оставаться на своем месте

2020-06-30 18:54 UTC, LenaMaltseva commented on frontend/src/components/Footer/UserFooter.module.scss
> +        margin-right: 40px;
настроить так, чтобы общий отступ от правого края не превращался в 160пикс вместо 120
независимо от количества "ссылок"

2020-06-30 18:54 UTC, LenaMaltseva commented on frontend/src/components/Forms/FeedbackForm.jsx
> +   }
я бы добавила asynс и await на выполнение отправки отзыва перед закрытием формы

2020-06-30 18:54 UTC, LenaMaltseva commented on frontend/src/components/Board/Board.jsx
> +               </div>
можно оптимизировать по аналогии со всплывающим окном в футере
и проверь шрифт, на макете Subtitle-1-Regular

2020-07-02 16:29 UTC, ASVVlasov requested changes

2020-07-02 16:29 UTC, ASVVlasov commented on backend/src/routes/feedback/index.js
>        feedback.user = req.user._id
это зачем? и ниже тоже

2020-07-02 16:29 UTC, ASVVlasov commented on frontend/src/components/Footer/UserFooter.jsx
> +               {/* <span className={styles.footer__link}>Поддержать проект</span> */}
убери если это не нужно

2020-07-02 16:29 UTC, ASVVlasov commented on frontend/src/components/Footer/Footer.jsx
> +      this.setState({ feedbackHintShown: !this.state.feedbackHintShown })
а где это используется? че-то я не увидел или я слепой)

2020-07-02 17:01 UTC, Konstantin-Buzuev commented on frontend/src/components/Footer/UserFooter.jsx
> +               {/* <span className={styles.footer__link}>Поддержать проект</span> */}
Как только добавиться функционал по поддержке проекта - станет нужно. Оставлю, чтобы помнить куда вставлять ссылку.

2020-07-02 17:11 UTC, Konstantin-Buzuev commented on frontend/src/components/Footer/Footer.jsx
> +      this.setState({ feedbackHintShown: !this.state.feedbackHintShown })
97 и 103 строки.
<Tune className={styles.footer__settingsBtn} onClick={this.FeedbackHintClick}/>
this.state.feedbackHintShown && styles.footer__feedback_show

2020-07-06 15:23 UTC, ASVVlasov submitted a review, later dismissed

2020-07-15 18:21 UTC, ASVVlasov approved these changes

2020-07-15 18:21 UTC, merged