feature/be42
ASVVlasov/Travel_Planner pull request #160
Opened 2020-07-29 19:33 UTC by ASVVlasov

2020-07-29 19:33 UTC, ASVVlasov commented
![](https://github.trello.services/images/mini-trello-icon.png) [Сделать разделение ответа 200 на message and data #BE42](https://trello.com/c/GdLHLbxQ/194-%D1%81%D0%B4%D0%B5%D0%BB%D0%B0%D1%82%D1%8C-%D1%80%D0%B0%D0%B7%D0%B4%D0%B5%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5-%D0%BE%D1%82%D0%B2%D0%B5%D1%82%D0%B0-200-%D0%BD%D0%B0-message-and-data-be42)

2020-07-31 10:55 UTC, Konstantin-Buzuev commented on frontend/src/redux/fetch/reducer.js
> +         }
По моему сюда travel: action.payload.data нужно добавить, иначе путешествие не обновится

2020-08-07 13:38 UTC, Konstantin-Buzuev commented on backend/src/models/types/errors.js
> +}
Нужно добавить еще на сброс и изменение пароля, добавление в контакты, и посылку фидбэка

2020-08-07 13:41 UTC, Konstantin-Buzuev commented on backend/src/routes/auth/forgot.js
>     })
Добавить message про сброс пароля

2020-08-07 13:44 UTC, Konstantin-Buzuev commented on backend/src/routes/feedback/index.js
> +         message: 'Мы получили ваше сообщение — спасибо за обратную связь, она помогает нам развиваться ‍🎓‍',
Это лучше в errors.js:success перенести, чтобы все в одном месте было.

2020-08-07 13:46 UTC, Konstantin-Buzuev commented on backend/src/routes/user/contact.js
> +         message: 'Друг получит приглашение на указанную почту, а пока мы добавили его в ваши контакты 😌',
Аналогично, это лучше в success.

2020-08-07 13:52 UTC, Konstantin-Buzuev requested changes
Minor changes requested

2020-08-07 14:36 UTC, Konstantin-Buzuev approved these changes

2020-08-07 14:37 UTC, merged