Feature/be44 (Поправить на бэке)
ASVVlasov/Travel_Planner pull request #161
Opened 2020-07-31 16:38 UTC by Konstantin-Buzuev

2020-07-31 16:39 UTC, Konstantin-Buzuev commented
![](https://github.trello.services/images/mini-trello-icon.png) [Поправить на бэке #BE44](https://trello.com/c/53gEu2AX/198-%D0%BF%D0%BE%D0%BF%D1%80%D0%B0%D0%B2%D0%B8%D1%82%D1%8C-%D0%BD%D0%B0-%D0%B1%D1%8D%D0%BA%D0%B5-be44)

2020-08-01 14:56 UTC, ASVVlasov requested changes

2020-08-01 14:56 UTC, ASVVlasov commented on backend/src/models/types/errors.js
> +   }),
это согласовано? что это?))))

2020-08-01 14:56 UTC, ASVVlasov commented on backend/src/routes/card/payer.js
> +      }
что это???? ты ищешь у текущего юзера во всех его путешествиях в карточках где он есть ?????? нах?

2020-08-01 14:56 UTC, ASVVlasov commented on backend/src/routes/user/contact.js
> +      console.log('userId- ', userId, ' type- ', typeof userId)
- консоль

2020-08-03 17:52 UTC, ASVVlasov approved these changes

2020-08-03 17:52 UTC, merged