Feature/be50: Dates fix
ASVVlasov/Travel_Planner pull request #174
Opened 2020-08-19 20:44 UTC by Konstantin-Buzuev

2020-08-20 18:33 UTC, Konstantin-Buzuev commented
![](https://github.trello.services/images/mini-trello-icon.png) [при обновлении названия поездки приходит варнинг про даты путешествия (см скрин) и поправить даты на бэке #BE50](https://trello.com/c/lRql44p6/203-%D0%BF%D1%80%D0%B8-%D0%BE%D0%B1%D0%BD%D0%BE%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B8-%D0%BD%D0%B0%D0%B7%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F-%D0%BF%D0%BE%D0%B5%D0%B7%D0%B4%D0%BA%D0%B8-%D0%BF%D1%80%D0%B8%D1%85%D0%BE%D0%B4%D0%B8%D1%82-%D0%B2%D0%B0%D1%80%D0%BD%D0%B8%D0%BD%D0%B3-%D0%BF%D1%80%D0%BE-%D0%B4%D0%B0%D1%82%D1%8B-%D0%BF%D1%83%D1%82%D0%B5%D1%88%D0%B5%D1%81%D1%82%D0%B2%D0%B8%D1%8F-%D1%81%D0%BC-%D1%81%D0%BA%D1%80%D0%B8%D0%BD-%D0%B8-%D0%BF%D0%BE%D0%BF%D1%80%D0%B0%D0%B2%D0%B8%D1%82%D1%8C-%D0%B4%D0%B0%D1%82%D1%8B-%D0%BD%D0%B0-%D0%B1%D1%8D%D0%BA%D0%B5-be50)

2020-08-21 17:15 UTC, ASVVlasov requested changes

2020-08-21 17:15 UTC, ASVVlasov commented on backend/src/models/travel.js
> +   return res
- убери let, аж глаз дергается, забудь это слово) только конст) 
- а что будешь делать если порядок карточке фронт поменяет?) тут надо по другому делать 
- ну и вообще для красоты можно это заменить на:
убрать if () return true
оставить  const res = ...
а дальше return res || (oldCards.length !== newCards.length)

2020-08-21 17:15 UTC, ASVVlasov commented on backend/src/models/travel.js
> +            }
т.е. если у тебя карточки не поменялись а поменялись только даты то все равно пробежишься по карточкам всем?

2020-08-21 19:14 UTC, ASVVlasov commented on backend/src/models/handlers/statusHandler.js
> +   if (doc.status !== travelStatuses.ARCHIVE && endDate < today) {
позаимствуй compare

2020-08-24 13:19 UTC, ASVVlasov approved these changes

2020-08-24 13:19 UTC, merged