Fix/fe10 (header)
ASVVlasov/Travel_Planner pull request #22
Opened 2020-05-01 04:05 UTC by rri9

2020-05-01 05:11 UTC, rri9 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Travel Page/ header bugfix #FE10](https://trello.com/c/7ozJ6L9j/53-travel-page-header-bugfix-fe10)

2020-05-01 10:01 UTC, ASVVlasov requested changes

2020-05-01 10:01 UTC, ASVVlasov commented on frontend/src/components/Header/Header.module.scss
> +
у тебя где-то контейнер под свг а где-то напряму в свг передаешь класс, нельзя сделать однообразно? Если это глобальное поведение вынеси сразу в глобальный файл. миксин flexCenter используешь один раз можно не плодить миксины

2020-05-01 10:01 UTC, ASVVlasov commented on frontend/src/components/Header/Header.module.scss
>    .user-profile {
вот это пока убери, у нас нет адаптива

2020-05-01 10:01 UTC, ASVVlasov commented on frontend/src/components/Header/Header.module.scss
> +    height: 14px;
по моему тут что-то не то с размерами, на макете вроде 24

2020-05-06 11:50 UTC, ASVVlasov submitted a review, later dismissed

2020-05-06 13:01 UTC, merged