Feature/fe16 (routing)
ASVVlasov/Travel_Planner pull request #23
Opened 2020-05-01 05:56 UTC by rri9

2020-05-01 05:57 UTC, rri9 commented
![](https://github.trello.services/images/mini-trello-icon.png) [travel Page / routing #FE16](https://trello.com/c/YTn7aIam/62-travel-page-routing-fe16)

2020-05-03 14:57 UTC, ASVVlasov requested changes

2020-05-03 14:57 UTC, ASVVlasov commented on frontend/src/index.js
> +      </Switch>
создай папку router в нем сделай компонент MainRouter и туда вынеси логику по роутеру, а из боарда вынести логику по роутеру в TravelPageRouter в той же папке

2020-05-03 14:57 UTC, ASVVlasov commented on frontend/src/index.js
>    <Provider store={store}>
вот это вот надо обернуть в HashRouter который импортируется из react-router-dom

2020-05-03 14:57 UTC, ASVVlasov commented on frontend/src/pages/TravelPage/TravelPage.jsx
> +        </Switch>
не уверен что мы обговаривали что у нас табы будут через роутер работать

2020-05-03 15:40 UTC, rri9 commented on frontend/src/index.js
>    <Provider store={store}>
HashRouter/BrowserRouter из react-router-dom заменен на ConnectedRouter из connected-react-router.

2020-05-04 12:11 UTC, ASVVlasov commented on frontend/src/index.js
>    <Provider store={store}>
Тогда сделай так чтобы у нас при обновлении страницы приложение переходило по текущему роуту, а не бек отдавал сообщение Cannot GET /travel/1/board/transport

2020-05-05 20:58 UTC, merged