Feature/FE9
ASVVlasov/Travel_Planner pull request #26
Opened 2020-05-02 14:40 UTC by Discipulus101

2020-05-02 14:41 UTC, Discipulus101 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Travel Page / header title #FE9](https://trello.com/c/ePQlbkua/67-travel-page-header-title-fe9)

2020-05-02 18:53 UTC, ASVVlasov requested changes
поправь немного функционал, я бы убрал вообще кнопки как я описал ниже в комменте

2020-05-02 18:53 UTC, ASVVlasov commented on frontend/src/controls/HeaderTitle/HeaderTitle.jsx
> +import { ReactComponent as InputBtnCanselSVG } from '../../assets/images/icons/clipboard.svg';
непонятные иконки при редактировании, можно сделать вообще без них, изменил поле, кликнул вне компонента - значение изменилось и поле обратно не редактируемое, и карандаш теперь уехал от названия

2020-05-03 22:26 UTC, ASVVlasov requested changes
на счет ширины на всю это хз, и шрифт стал другой в заголовке(

2020-05-03 22:26 UTC, ASVVlasov commented on frontend/src/controls/HeaderTitle/HeaderTitle.jsx
> +        this.handleKeyUp = this.handleKeyUp.bind(this);
вот это вообще не нужно, у тебя все функции стрелочные

2020-05-04 10:36 UTC, Discipulus101 commented on frontend/src/controls/HeaderTitle/HeaderTitle.jsx
> +        this.handleKeyUp = this.handleKeyUp.bind(this);
Удалил .bind(this)
По поводу другого шрифта- он изменился в макете, поэтому сделал как сейчас там указано. Целиком в Header шрифт не менял, т.к. не моя задача, но если нужно то и там поправлю.

2020-05-05 20:02 UTC, ASVVlasov requested changes

2020-05-05 20:02 UTC, ASVVlasov commented on frontend/src/controls/HeaderTitle/HeaderTitle.jsx
> +                inputSize: evt.target.value.length
сделай тут чтобы не уезжала надпись влево, допустим length + 2 чтобы с запасом было

2020-05-05 22:43 UTC, Discipulus101 commented on frontend/src/controls/HeaderTitle/HeaderTitle.jsx
> +                inputSize: evt.target.value.length
Исправил

2020-05-06 11:46 UTC, ASVVlasov approved these changes

2020-05-06 11:46 UTC, merged