feat(TransportAddForm): init
ASVVlasov/Travel_Planner pull request #27
Opened 2020-05-02 19:20 UTC by mary4erry

2020-05-06 11:05 UTC, mary4erry commented
![](https://github.trello.services/images/mini-trello-icon.png) [Travel Page / transport board / add-form #FE12](https://trello.com/c/xlRF3nuH/63-travel-page-transport-board-add-form-fe12)

2020-05-06 12:12 UTC, ASVVlasov requested changes
скачай плагин Prettier в VSCode и настрой его на автоформатирование при сохранении, у тебя в коде ; их быть не должно

2020-05-09 12:18 UTC, ASVVlasov requested changes
у тебя на кнопки добавить и отменить при нажатии на кнопку ставится синяя рамка надо :focus,:active{outline:none} сделать

2020-05-09 15:06 UTC, ASVVlasov approved these changes

2020-05-09 15:06 UTC, merged