feature/BE11: files API
ASVVlasov/Travel_Planner pull request #35
Opened 2020-05-04 13:06 UTC by ASVVlasov

2020-05-04 13:06 UTC, ASVVlasov commented
![](https://github.trello.services/images/mini-trello-icon.png) [API attachment #BE11](https://trello.com/c/Oyf6nzG9/64-api-attachment-be11)

2020-05-04 15:00 UTC, Konstantin-Buzuev requested changes

2020-05-04 15:00 UTC, Konstantin-Buzuev commented on backend/src/controllers/file/upload.js
> +
Уже есть контроллер attachment.js, в который нужно прикрутить этот код.

2020-05-04 15:00 UTC, Konstantin-Buzuev commented on backend/src/routes/files.js
> +router.use('/', express.static(path.resolve(__dirname, '..', 'uploads')))
см. коммент выше

2020-05-06 11:56 UTC, Konstantin-Buzuev commented on backend/src/controllers/card/attachment.js
> +         path: generatedFileName,
То есть возвращает по сути Attachment.

2020-05-06 11:58 UTC, Konstantin-Buzuev commented on backend/src/controllers/card/attachment.js
> +      })
Тогда нужно заменить на let newAttachment = new Attachment(path). Пусть не совсем корректно по написанию, зато по коду верно.

2020-05-06 12:00 UTC, ASVVlasov commented on backend/src/controllers/card/attachment.js
> +         path: generatedFileName,
не стал переделывать, ибо потом у тебя в модели это используется, только вместо пути будет по сути md5 имя файла которое фронт знает где брать

2020-05-06 12:04 UTC, Konstantin-Buzuev commented on backend/src/models/board.js
> +const EntertaimentCard = require("./entertainment.js").schema
Тут у меня косяк, забыл букву N добавить. Исправлю в будущем.

2020-05-06 12:06 UTC, ASVVlasov commented on backend/src/models/board.js
> +const EntertaimentCard = require("./entertainment.js").schema
зачем это в ревью писать тем более что судя по коду буква n как раз добавлена

2020-05-06 12:08 UTC, Konstantin-Buzuev approved these changes

2020-05-06 12:09 UTC, merged