Feature/be7
ASVVlasov/Travel_Planner pull request #39
Opened 2020-05-06 16:43 UTC by ASVVlasov

2020-05-06 16:43 UTC, ASVVlasov commented
![](https://github.trello.services/images/mini-trello-icon.png) [Travel Page /transport board/API #BE7](https://trello.com/c/GLsmW7Si/56-travel-page-transport-board-api-be7)

2020-05-07 09:14 UTC, Konstantin-Buzuev commented on backend/src/controllers/board/boardController.js
> +            return
Сейчас errorHandler возвращает объект, поэтому return надо переместить в 16 строку.

2020-05-07 09:14 UTC, Konstantin-Buzuev commented on backend/src/controllers/board/boardController.js
> +            return
Аналогично

2020-05-07 09:19 UTC, Konstantin-Buzuev commented on backend/src/controllers/board/boardController.js
> +         return board
У меня сейчас возвращается из контроллера объект {status: [200/400/500], result: [item/error message]}. Сделано для того, чтобы форма ответа была унифицирована и при корректной работе и при ошибках (так-то я помню, что res.json возвращает statusCode=200). Предлагаю обсудить и принять один подход.

2020-05-07 09:19 UTC, Konstantin-Buzuev commented on backend/src/controllers/board/boardController.js
> +            return
return аналогично

2020-05-07 09:19 UTC, Konstantin-Buzuev commented on backend/src/controllers/board/boardController.js
> +            return
Аналогично

2020-05-07 09:20 UTC, Konstantin-Buzuev commented on backend/src/controllers/board/boardController.js
> +         }
См. выше про возвращаемый объект

2020-05-07 09:24 UTC, Konstantin-Buzuev commented on backend/src/controllers/board/boardController.js
> +         }
Не прокатит, т.к. если выполнение дошло до этого места значит есть уже как минимум одно непустое поле - boardID. Смысл был в том, что в body передается boardID и updatingBoard, который содержит обновляемые поля. И вот если уже сам updatingBoard(имя условно) - пустой, то на этой проверке ему вылетает сообщение об ошибке ("нечего обновлять, чувак!").

2020-05-07 09:25 UTC, Konstantin-Buzuev commented on backend/src/controllers/board/boardController.js
> +            }
Еще одна причина по которой boardID нужно вынести из board, а то в документе появится новое поле. )))

2020-05-07 09:26 UTC, Konstantin-Buzuev commented on backend/src/controllers/board/boardController.js
> +      } catch (err) {
Про возвращаемый объект уже писал

2020-05-07 09:33 UTC, Konstantin-Buzuev commented on backend/src/routes/board.js
> +})
В возвращаемый объект, по хорошему, надо еще добавить ту инфу, которая нужна будет фронту для отрисовки. Как минимум, для хедера - массив объектов вида {travelerID, nickname, avatarPath}.
Либо фронтовики будут обращаться к API, чтобы получить инфу об участниках поездки.

2020-05-07 09:36 UTC, Konstantin-Buzuev requested changes
В целом - несколько опечаток и пара вопросов, которые просто надо согласовать между собой, чтобы выступать единым <strike>фронтом</strike> бэком.

2020-05-09 11:55 UTC, Konstantin-Buzuev submitted a review, later dismissed

2020-05-09 12:14 UTC, merged