Feature/FE8
ASVVlasov/Travel_Planner pull request #42
Opened 2020-05-09 11:14 UTC by Discipulus101

npm install react-dates

2020-05-09 11:16 UTC, Discipulus101 commented
![](https://github.trello.services/images/mini-trello-icon.png) [calendar #FE8](https://trello.com/c/1KPYcm0U/66-calendar-fe8)

2020-05-09 12:29 UTC, ASVVlasov requested changes

2020-05-09 12:29 UTC, ASVVlasov commented on frontend/src/controls/Calendar/Calendar.jsx
> +import { DateRangePicker } from 'react-dates';
как ты поставил этот пакет если его нет в package.json? из-за этого падает хироку

2020-05-09 16:06 UTC, Discipulus101 commented on frontend/src/controls/Calendar/Calendar.jsx
> +import { DateRangePicker } from 'react-dates';
Исправил

2020-05-10 12:59 UTC, ASVVlasov approved these changes

2020-05-10 12:59 UTC, merged