Feature/FE19
ASVVlasov/Travel_Planner pull request #45
Opened 2020-05-11 01:04 UTC by LenaMaltseva

2020-05-11 01:05 UTC, LenaMaltseva commented
![](https://github.trello.services/images/mini-trello-icon.png) [Travel Page / board Actions/Reducers #FE19](https://trello.com/c/2dbTwB2e/77-travel-page-board-actions-reducers-fe19)

2020-05-13 13:56 UTC, ASVVlasov requested changes

2020-05-13 13:56 UTC, ASVVlasov commented on frontend/src/redux/actions/cards.actions.js
> +         .catch((err) => dispatch(deleteCardError(err)))
а тут забыла переделать? )

2020-05-13 13:59 UTC, LenaMaltseva commented on frontend/src/redux/actions/cards.actions.js
> +         .catch((err) => dispatch(deleteCardError(err)))
нет, т.к. тут мне не нужен res.json(), с бэка возвращается пустой объект

2020-05-13 13:59 UTC, ASVVlasov approved these changes

2020-05-13 14:06 UTC, ASVVlasov approved these changes

2020-05-13 14:09 UTC, merged