Feature/be14 (Swagger-документация на API)
ASVVlasov/Travel_Planner pull request #48
Opened 2020-05-12 11:03 UTC by Konstantin-Buzuev

2020-05-12 11:36 UTC, Konstantin-Buzuev commented
![](https://github.trello.services/images/mini-trello-icon.png) [Swagger-документация на API #BE14](https://trello.com/c/NoQhHHpD/76-swagger-%D0%B4%D0%BE%D0%BA%D1%83%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%86%D0%B8%D1%8F-%D0%BD%D0%B0-api-be14)

2020-05-13 12:23 UTC, ASVVlasov requested changes

2020-05-13 12:23 UTC, ASVVlasov commented on backend/src/docs/card.swagger.js
> +                  fileName: {
file у нас поле а не fileName

2020-05-13 13:04 UTC, ASVVlasov approved these changes

2020-05-13 13:04 UTC, merged