Feature/FE21
ASVVlasov/Travel_Planner pull request #54
Opened 2020-05-14 10:30 UTC by LenaMaltseva

2020-05-14 10:36 UTC, LenaMaltseva commented
![](https://github.trello.services/images/mini-trello-icon.png) [Travel Page / transport board / add-form Actions/Reducers #FE21](https://trello.com/c/PkglCmYr/79-travel-page-transport-board-add-form-actions-reducers-fe21)

2020-05-15 14:30 UTC, ASVVlasov requested changes

2020-05-15 14:30 UTC, ASVVlasov commented on frontend/src/components/CardForm/CardForm.jsx
> +)
это получается контрол у нас? что он тут делает? ))))

2020-05-15 14:30 UTC, ASVVlasov commented on frontend/src/components/CardForm/CardForm.module.scss
> +   top: 20px;
.icon {
&__cross{...}
}

2020-05-15 14:41 UTC, LenaMaltseva commented on frontend/src/components/CardForm/CardForm.jsx
> +)
Обсуждали ведь, что он будет пока тут, а если в таком же виде его потом можно будет применить в другой форме, то вынесем в контролы. Если что-то изменилось, могу вынести сейчас..

2020-05-15 14:42 UTC, LenaMaltseva commented on frontend/src/components/CardForm/CardForm.module.scss
> +   top: 20px;
Если иконок несколько могу понять, но иконка тут всего одна... Может лучше тогда просто убрать "__cross"
p.s. почему верстка не была отревьюена на этапе создания формы в рамках другой задачи?)

2020-05-15 14:48 UTC, ASVVlasov approved these changes

2020-05-15 14:48 UTC, merged