Feature/fe18
ASVVlasov/Travel_Planner pull request #60
Opened 2020-05-16 15:38 UTC by Discipulus101

2020-05-16 18:16 UTC, ASVVlasov requested changes

2020-05-16 18:16 UTC, ASVVlasov commented on frontend/src/controls/Calendar/Calendar.jsx
> +   chengeAmountOfDays = (startDate, endDate) => {
change )

2020-05-16 18:16 UTC, ASVVlasov commented on frontend/src/redux/actions/header.actions.js
> +   }
а если ошибка прилетит с сервака? то фронт упадет да? )

2020-05-16 22:57 UTC, Discipulus101 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Travel Page / Header Actions/Reducers #FE18](https://trello.com/c/Fdw8NTAO/72-travel-page-header-actions-reducers-fe18)

2020-05-19 14:42 UTC, ASVVlasov requested changes
ты создал в редаксе header/actions, operations - они не нужны(ты работаешь не с хедером а с данными) я создал же там папку travel, туда только добавь нужные экшны и редьюсеры, и называй их по смыслу модели - т.е. вместо getHeader - getTravel из которого ты возьмешь и тайтл и пользаков и даты, к примеру.

2020-05-19 14:42 UTC, ASVVlasov commented on frontend/src/controls/Calendar/Calendar.jsx
> +         endDate: convertedEndDate,
это надо по хорошему вынести наружу ибо если где-то еще будем менять даты то будут меняться только в тревеле, ну ладно, у нас поидее будет другой компонент в карточке

2020-05-19 14:42 UTC, ASVVlasov commented on frontend/src/components/Header/Header.jsx
> +})
назови не headerReducer а travelReducer ты же работаешь с путешествием, также метод getHeader - getTravel например

2020-05-19 14:42 UTC, ASVVlasov commented on frontend/src/components/Header/Header.jsx
> +            </div>
это тоже нужно подтянуть с бэка

2020-05-19 18:25 UTC, ASVVlasov requested changes
все почти норм, только немного минимизируй это все)

2020-05-19 18:25 UTC, ASVVlasov commented on frontend/src/redux/travel/actions.js
> +})
зачем так много экшнов по каждому полю когда апишка одна? ты можешь создать один экшн на тревел и его дергать когда тебе надо изменить путешествие и передавать туда объект travel

2020-05-19 18:25 UTC, ASVVlasov commented on frontend/src/redux/travel/operations.js
> +   fetchRequest.put(MAIN_URL, changeTravelDateSuccess, date)
по поводу изменения каждого поля в отдельности уже писал выше

2020-05-19 18:25 UTC, ASVVlasov commented on frontend/src/redux/travel/operations.js
> +
это вообще не нужно, у нас есть fetchRequest.get куда передается линк, и экшн который потом вызовется после ответа от сервера, смотри выше на 14 строчке getSummary - он вызывает fetchRequest.get куда я просто передаю ссылку и экшн

2020-05-19 18:25 UTC, ASVVlasov commented on frontend/src/redux/travel/reducer.js
> +   cards: [],
это все, ну кроме errorMessage(да и то оно пока не реализовано можно выпилить), можно заменить travel и тебе в хедер будет прилетать объект в котором ты уже можешь взять любое нужное тебе поле

2020-05-19 18:25 UTC, ASVVlasov commented on frontend/src/redux/travel/reducer.js
> +      }
не совсем понял для чего этот экшн? если ты хотел делать что-то перед загрузкой данных, типа прелоадера - опять же его еще нет и это в принципе не нужно, тем более что отдает тебе весь стор ничего не меняя....

2020-05-19 18:25 UTC, ASVVlasov commented on frontend/src/redux/travel/reducer.js
> +      }
вот это все если учесть то что выше по ревью писал можно заменить на 1 экшн 
```
case ... : {
   return {
      ...state,
      travel: action.payload
   }
}
```

2020-05-19 22:36 UTC, ASVVlasov approved these changes

2020-05-19 22:36 UTC, merged