Feature/be22
ASVVlasov/Travel_Planner pull request #70
Opened 2020-05-21 19:36 UTC by Konstantin-Buzuev

1. В роутере нет добавления/удаления документов, поскольку их пока не планируется реализовывать.
2. Добавления/удаления путешествия также нет, т.к. это должно быть реализовано в роутере travel.

2020-05-21 19:39 UTC, Konstantin-Buzuev commented
![](https://github.trello.services/images/mini-trello-icon.png) [Роутер - user #BE22](https://trello.com/c/7sCn0zc0/126-%D1%80%D0%BE%D1%83%D1%82%D0%B5%D1%80-user-be22)

2020-05-21 21:10 UTC, ASVVlasov requested changes

2020-05-21 21:10 UTC, ASVVlasov commented on backend/src/routes/user/contact.js
> +)
сделай selfId = mock.[something] и почему опять пут? у нас добавление нового контакта, как в других апихах у нас сделано - надо однотипно сделать

2020-05-21 21:10 UTC, ASVVlasov commented on backend/src/routes/user/index.js
> +)
тут не нужен userId в параметрах, если мы хотим получить инфу о текущем юзере сейчас айдишник из моков возьмется - потом с авторизации

2020-05-21 21:10 UTC, ASVVlasov commented on backend/src/routes/user/index.js
> +   })
а выше тогда запрос зачем он? т.е. любой пользак сможет запросить инфу о юзере любую?) с логином и паролем? )

2020-05-21 21:10 UTC, ASVVlasov commented on backend/src/routes/user/index.js
> +)
нужно замокать айдишник а вообще а я бы такие апишки пока бы не делал или заведомо айдишник не передавал чтобы запрос сфелился) чтобы избежать ошибок прошлого)

2020-05-22 10:21 UTC, ASVVlasov approved these changes

2020-05-22 10:22 UTC, merged