feat(TravelPage): edit styles
ASVVlasov/Travel_Planner pull request #74
Opened 2020-05-22 15:01 UTC by mary4erry

2020-05-24 18:16 UTC, mary4erry commented
![](https://github.trello.services/images/mini-trello-icon.png) [Travel Page / Привести дизайн в соответствие с макетом #FE30](https://trello.com/c/h7LAPcNA/101-travel-page-%D0%BF%D1%80%D0%B8%D0%B2%D0%B5%D1%81%D1%82%D0%B8-%D0%B4%D0%B8%D0%B7%D0%B0%D0%B9%D0%BD-%D0%B2-%D1%81%D0%BE%D0%BE%D1%82%D0%B2%D0%B5%D1%82%D1%81%D1%82%D0%B2%D0%B8%D0%B5-%D1%81-%D0%BC%D0%B0%D0%BA%D0%B5%D1%82%D0%BE%D0%BC-fe30)

2020-05-25 23:56 UTC, LenaMaltseva requested changes
Комменты оставила по ходу кода + из дополнений, что там не вписать:
- в CardFull шапку "стоимость" с иконкой надо прижать к правому краю (как сами цифры);
- и пробегись поиском по проекту на предмет старых цветов - как минимум не стилизован UserPicker

2020-05-25 23:56 UTC, LenaMaltseva commented on frontend/src/styles/_mixins.scss
> +   font-weight: 600;
Откуда это? 500 должно быть

2020-05-25 23:56 UTC, LenaMaltseva commented on frontend/src/pages/TravelPage/TravelPage.module.scss
>      display: flex;
убрать $width,
импортировать цвета,
цвет фона установить как в твоем комментарии

2020-05-25 23:56 UTC, LenaMaltseva commented on frontend/src/styles/_mixins.scss
> +  filter: drop-shadow( 1px 4px 20px change-color($color-secondary-main, $alpha: 0.6));
кнопке оставить ее box-shadow, как было
а 54-55 строки вынести в отдельный @mixin IconShadow
после чего поправить в IconActive на @include IconShadow и добавить туда opacity: 1

2020-05-25 23:56 UTC, LenaMaltseva commented on frontend/src/controls/Switch/Switch.jsx
> +               /> }
в фигурные скобки див оборачивать не надо

2020-05-25 23:56 UTC, LenaMaltseva commented on frontend/src/components/Cards/CardFull.jsx
> +               )}
здесь пропали стили для обычных пользователей
```
className={classNames( styles.travelers__name,
    payer.user._id === userId && styles.travelers__name_itsMe
)}
```

2020-05-25 23:56 UTC, LenaMaltseva commented on frontend/src/components/Cards/CardFull.jsx
> +               payer.user._id === userId && styles.card__cost_myCoastPayed)
два одинаковых условия, во второй строке должно быть:
`payer.user._id === userId && payer.hasPayed && styles.card__cost_myCostPayed`

2020-05-25 23:56 UTC, LenaMaltseva commented on frontend/src/components/Cards/CardFull.module.scss
>     }
приложение для путешествий)) но cost :)

2020-05-25 23:56 UTC, LenaMaltseva commented on frontend/src/components/Cards/CardFull.jsx
> +                              beginDate <= today && styles.schema__point_currentDate)}
здесь и ниже
`start === today && styles.schema__point_currentDate`
иначе все прошедшие даты тоже светятся зеленым

2020-05-25 23:56 UTC, LenaMaltseva commented on frontend/src/components/Cards/CardFull.jsx
> +                                 endDate <= today && styles.schema__path_currentDate)} />
здесь и ниже
`finish === today && styles.schema__point_currentDate`

2020-05-25 23:56 UTC, LenaMaltseva commented on frontend/src/components/Cards/CardFull.jsx
> +      let today = (new Date()).toISOString()
наша задача сравнить дату без времени - например с .toLocaleDateString()
и для этого преобразовать даты, прилетающие с бэка, к такому же виду
аналогично сделать в CardShort
```
const today = new Date().toLocaleDateString()
const start = new Date(beginDate).toLocaleDateString()
const finish = new Date(endDate).toLocaleDateString()
```

2020-05-25 23:56 UTC, LenaMaltseva commented on frontend/src/components/Cards/CardShort.module.scss
> +      @include Caption-1-SemiBold;
здесь было правильно до этого:
`@include Caption-1-Regular;`

2020-05-25 23:56 UTC, LenaMaltseva commented on frontend/src/components/Cards/CardShort.module.scss
> +      }
а SemiBold должно быть здесь

2020-05-25 23:56 UTC, LenaMaltseva commented on frontend/src/components/Cards/CardShort.module.scss
>     }
стили по макету другие и для аватарок есть миксины

2020-05-25 23:56 UTC, LenaMaltseva commented on frontend/src/components/Footer/Footer.jsx
> +               </button>
Иконки нет нужды оборачивать в кнопку, в этом компоненте итак доступен onClick, а больше нам и не надо, соот-но, и здесь код сократится, и в стилях
`<Tune className={styles.footer__settingsBtn}/>`

2020-05-25 23:56 UTC, LenaMaltseva commented on frontend/src/components/Footer/footer.module.scss
>      }
с 46й по 63ю можно заменить на:
```
&__settingsBtn {
   @include IconBright(40px);
   margin-left: 55px;     
}
```

2020-05-25 23:56 UTC, LenaMaltseva commented on frontend/src/components/Sidebar/Sidebar.module.scss
>  }
подредактировать миксины и тут будет:
```
.sidebar__link svg { 
    @include IconLight(40);
}
.sidebar__link_active svg{
    @include IconActive;
}
```

2020-05-25 23:56 UTC, LenaMaltseva commented on frontend/src/components/Cards/CardShort.module.scss
>        fill: $color-gray-5;
$color-gray-5?

2020-05-26 13:33 UTC, mary4erry commented on frontend/src/components/Cards/CardFull.jsx
> +                              beginDate <= today && styles.schema__point_currentDate)}
а вот тут я так и думала, что все что сегодня и прошло уже, то горит завершенным

2020-05-26 15:05 UTC, LenaMaltseva requested changes

2020-05-26 15:05 UTC, LenaMaltseva commented on frontend/src/components/Cards/CardFull.jsx
> +               payer.user._id === userId  && payer.hasPayed && styles.card__cost_myCoastPayed)
эти стили не срабатывают

2020-05-26 15:05 UTC, LenaMaltseva commented on frontend/src/styles/_mixins.scss
> + }
а что это?

2020-05-26 15:05 UTC, LenaMaltseva commented on frontend/src/components/Cards/CardFull.jsx
> +
как насчет выпилить?

2020-05-26 15:05 UTC, LenaMaltseva commented on frontend/src/pages/TravelPage/TravelPage.module.scss
> +@import '../../styles/colors', '../../styles/mixins', '../../styles/colors';
ооу) видать в прошлый раз эти строки были скрыты в гите, я не видела что импорты есть)
достаточно одного импорта colors :)) а миксины здесь не используются

2020-05-26 15:51 UTC, mary4erry commented on frontend/src/styles/_mixins.scss
> + }
это я зачем то перенесла из хэдера, и забыла убрать, ведь я хэдер не трогаю сейчас)

2020-05-26 17:25 UTC, LenaMaltseva approved these changes
Job's done, congrats)

2020-05-26 20:06 UTC, merged