feature/fe24 datepicker
ASVVlasov/Travel_Planner pull request #86
Opened 2020-05-24 19:38 UTC by ASVVlasov

2020-05-24 19:38 UTC, ASVVlasov commented
![](https://github.trello.services/images/mini-trello-icon.png) [Travel Page / Доработать поле дат на форме под календарь FE#24](https://trello.com/c/OaivijyS/89-travel-page-%D0%B4%D0%BE%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%B0%D1%82%D1%8C-%D0%BF%D0%BE%D0%BB%D0%B5-%D0%B4%D0%B0%D1%82-%D0%BD%D0%B0-%D1%84%D0%BE%D1%80%D0%BC%D0%B5-%D0%BF%D0%BE%D0%B4-%D0%BA%D0%B0%D0%BB%D0%B5%D0%BD%D0%B4%D0%B0%D1%80%D1%8C-fe24)

2020-05-25 21:08 UTC, LenaMaltseva requested changes
выйди и зайди нормально))

2020-05-26 12:38 UTC, LenaMaltseva submitted a review, later dismissed

2020-05-26 12:38 UTC, LenaMaltseva commented on frontend/src/controls/Input/InputControl.jsx
> +import MultiSelect from 'react-multi-select-component'
> Compiled with warnings: 'MultiSelect' is defined but never used

2020-05-26 15:40 UTC, LenaMaltseva approved these changes

2020-05-26 15:48 UTC, merged