feat(TravelPage/Header): remake Header
ASVVlasov/Travel_Planner pull request #87
Opened 2020-05-24 23:29 UTC by Discipulus101

refactoring HeaderTitle
change calendar colors
added UserPicker to Header
added burger menu

2020-05-24 23:30 UTC, Discipulus101 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Travel Page / Доработать Header по макету #FE26](https://trello.com/c/nqA2AV46/105-travel-page-%D0%B4%D0%BE%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%B0%D1%82%D1%8C-header-%D0%BF%D0%BE-%D0%BC%D0%B0%D0%BA%D0%B5%D1%82%D1%83-fe26)

2020-05-25 12:51 UTC, ASVVlasov requested changes
почисти код, наведи порядок в стилях
если почистить перзист то у тебя падает фронт! это происходит потому что как раз ты отрисовываешь нафига-то главного юзера в рендере
надо сделать чтобы закрывалось меню по клику вне этого меню

2020-05-25 12:51 UTC, ASVVlasov commented on frontend/src/components/Header/Header.jsx
> +      return usersArray
вот это все превращается в return users.map((user) => `<div>...</div>`)

2020-05-25 12:51 UTC, ASVVlasov commented on frontend/src/components/Header/Header.jsx
> +   FILE_URL = 'http://localhost:3300/card/file/'
на хироку поломается - тут надо сделать как в борде через условие

2020-05-25 12:51 UTC, ASVVlasov commented on frontend/src/components/Header/Header.jsx
> +                     this.openForm('UserPicker')
вынеси в отдельный метод

2020-05-25 12:51 UTC, ASVVlasov commented on frontend/src/components/Header/Header.jsx
> +               </div>
зачем ты выводишь пользователя когда он к нам приходит в массиве users в путешествии(у тебя есть метод по выводу пользаков - там просто проверку сделай по _id и нужный класс вставляй

2020-05-25 12:51 UTC, ASVVlasov commented on frontend/src/components/Header/Header.module.scss
> +.travellers__item_mainUser {
убери отсюда .travellers__item_mainUser он у тебя внутри лежит

2020-05-25 12:51 UTC, ASVVlasov commented on frontend/src/components/Header/Header.module.scss
> +  }
а где миксины на аву?

2020-05-25 12:51 UTC, ASVVlasov commented on frontend/src/components/Header/Header.module.scss
> +    top: calc(233% - 94px/2);
Что это за хуйня?!

2020-05-25 12:51 UTC, ASVVlasov commented on frontend/src/controls/Calendar/Calendar.css
>      border: none!important;
если я правильно помню, Лена говорила что это как-то по другому настраивается(без important)

2020-05-25 12:51 UTC, ASVVlasov commented on frontend/src/controls/Calendar/Calendar.css
> +    border-right: 33px solid #2F80ED!important;;
цвета не все настроены(рейнж не тем цветом когда выделяем даты и нижнее подчеркивание у дат)

2020-05-25 12:51 UTC, ASVVlasov commented on frontend/src/controls/Calendar/Calendar.css
> +    border-right: 33px solid #2F80ED!important;;
и у нас цвета есть в переменных и почему .css?

2020-05-25 12:51 UTC, ASVVlasov commented on frontend/src/controls/UserPicker/UserPicker.jsx
> +         console.log('addUserHandler', { cardId, userId })
убери консоль

2020-05-25 14:44 UTC, LenaMaltseva commented on frontend/src/controls/Calendar/Calendar.css
>      border: none!important;
если верить документации в самом файле компоненте достаточно одного параметра: 
<DateRangePicker ... **noBorder={true}** />

2020-05-25 15:17 UTC, LenaMaltseva requested changes
Если запрошено ревью по части макета :) то вот:
- цвета кнопки "назад", названия и дат поездки, иконок редактирования - старые
- если пользователь один в своей же поездке, то вместо его аватарки и круглой кнопки отображается большая жирная синяя кнопка "добавить участников" (посмотри на макете, пожалуйста)
- если помимо создателя появился еще кто-то, то аватарки и маленькая кнопка. При этом кнопка должна быть поверх аватарки, а не под ней (-> макет)

Из того, что уже и Саша упоминал:
- пользователи без аватарки не по макету, у нас есть миксины 
- в календаре цвета подправить
- меню должно закрывается при клике вне

2020-05-26 20:42 UTC, ASVVlasov requested changes
и стрелка назад не работает сделай переход на юзер пейдж

2020-05-26 20:42 UTC, ASVVlasov commented on frontend/src/components/Header/Header.module.scss
> +    font-weight: 500;
у нас на это разве нет миксина?

2020-05-26 20:42 UTC, ASVVlasov commented on frontend/src/components/Header/Header.module.scss
> +  }
есть контрол с этой кнопкой

2020-05-26 21:38 UTC, ASVVlasov approved these changes

2020-05-26 21:38 UTC, ASVVlasov approved these changes

2020-05-26 21:46 UTC, ASVVlasov requested changes

2020-05-26 21:46 UTC, ASVVlasov commented on frontend/src/components/Header/Header.jsx
> +   }
что это? у нас есть роутер

2020-05-26 22:17 UTC, LenaMaltseva requested changes

2020-05-26 22:17 UTC, LenaMaltseva commented on frontend/src/components/Header/Header.jsx
> +                  />
здесь не хватает параметра kind="action", чтобы соответствовало макету

2020-05-26 22:17 UTC, LenaMaltseva commented on frontend/src/components/Header/Header.module.scss
> +    font-size: 14px;
стяни, пожалуйста, dev
здесь миксин Сaption 1 SemiBold

2020-05-26 22:17 UTC, LenaMaltseva commented on frontend/src/components/Header/Header.module.scss
> +    font-size: 14px;
здесь тоже Сaption 1 SemiBold

2020-05-26 22:17 UTC, LenaMaltseva commented on frontend/src/controls/Calendar/Calendar.module.scss
> +        cursor: pointer;
кроме маржина @include IconLight(24px);

2020-05-26 22:17 UTC, LenaMaltseva commented on frontend/src/controls/Calendar/Calendar.jsx
> +               <EditBtnSVG />
зачем эта кнопка, если она ничего не делает?
надо чтобы редачились даты

2020-05-26 22:17 UTC, LenaMaltseva commented on frontend/src/controls/HeaderTitle/HeaderTitle.module.scss
> +    cursor: pointer;
кроме маржина @include IconLight(24px);

2020-05-26 22:17 UTC, LenaMaltseva commented on frontend/src/components/Header/Header.module.scss
>  }
@include IconBright(30px);

2020-05-26 22:17 UTC, LenaMaltseva commented on frontend/src/components/Header/Header.module.scss
> +  }
кнопка по макету впереди аватарок, например z-index: 100; пожалуйста

2020-05-26 22:17 UTC, LenaMaltseva commented on frontend/src/components/Header/Header.jsx
> +               <BackBtnSVG onClick={this.returnToPreviousPage} />
`onClick={ () => this.props.push('/profile/travels') }`
push импортится из 'connected-react-router' и подключается в mapDispatchToProps
вместо returnToPreviousPage (в результате которой получаем "Cannot GET /profile/travels")

2020-05-27 11:52 UTC, ASVVlasov approved these changes

2020-05-27 12:06 UTC, LenaMaltseva approved these changes

2020-05-27 12:06 UTC, LenaMaltseva commented on frontend/src/controls/Calendar/Calendar.jsx
> +import Button from '../../controls/Button/Button'
Зачем она здесь?)

2020-05-27 12:29 UTC, merged