Feature/fe33(HomePage/Slider)
ASVVlasov/Travel_Planner pull request #93
Opened 2020-05-26 16:48 UTC by Konstantin-Buzuev

2020-05-27 14:15 UTC, Konstantin-Buzuev commented
![](https://github.trello.services/images/mini-trello-icon.png) [Home Page #FE33](https://trello.com/c/tbUkfs7j/107-home-page-fe33)

2020-06-02 21:37 UTC, ASVVlasov requested changes

2020-06-02 21:37 UTC, ASVVlasov commented on frontend/src/components/Registartion/Registration.jsx
> +   passwordIsValid = (value) => (value.length >= 6 ? true : false)
just - value.length >= 6, but value.length > 7 - are better way

2020-06-02 21:37 UTC, ASVVlasov commented on frontend/src/components/Registartion/Registration.jsx
> +      let reg = new RegExp('[^@]+@[^@]+.[^@]+')
as@vv@gm.dsd - вот такая почта тоже подходит под этот регэксп, ладно это не так критично

2020-06-02 21:37 UTC, ASVVlasov commented on frontend/src/components/Registartion/Registration.jsx
> +      authInfo.rememberMe = this.state.rememberMe
const authInfo = { email, password, rememberMe } = this.state

2020-06-02 21:37 UTC, ASVVlasov commented on frontend/src/components/Registartion/Registration.jsx
> +      let tabs = this.state.tabs
const

2020-06-02 21:37 UTC, ASVVlasov commented on frontend/src/components/Registartion/Registration.jsx
> +         tabs[index].emailLabel = index ? 'Введите почту' : ''
напиши тут явно index === 0 - чтобы было понятно что ты проверяешь не просто наличие индекса а именно какая вкладка открыта( вообще поидее надо было делать не массив а объект наверное хз)

2020-06-02 21:37 UTC, ASVVlasov commented on frontend/src/components/Registartion/Registration.jsx
> +      this.props.authorization(authInfo, '/' + this.props.match.params.tab)
const res = await this.props........... - if (res) { push(....)} else { fuck you.... )))))) }

2020-06-02 21:37 UTC, ASVVlasov commented on frontend/src/components/Registartion/Registration.jsx
> +            activeClassName={styles['tabs-link_active']}
договорились в camelCase писать

2020-06-02 21:37 UTC, ASVVlasov commented on frontend/src/components/Registartion/Registration.jsx
> +            <nav className={styles['tabs']} children={this.mapTabsToRender()} />
styles.form, styles.tabs

2020-06-02 21:37 UTC, ASVVlasov commented on frontend/src/components/Registartion/Registration.module.scss
> +}
у тебя как-то неправильно prettier работает мне кажется - тут должна быть пустая строка в конце файла
Где БЭМ????

2020-06-02 21:37 UTC, ASVVlasov commented on frontend/src/components/Slider/Slider.module.scss
> +    top: 218px;
опять во всем файле нет БЭМ

2020-06-02 21:37 UTC, ASVVlasov commented on frontend/src/pages/HomePage/HomePage.jsx
> +               <LogoIcon className={styles['icon']} />
camelCase + БЭМ

2020-06-02 21:37 UTC, ASVVlasov commented on frontend/src/redux/auth/operations.js
> +      throw new Error(res.statusText)
а собственно куда тебе выплюнет ошибку если не будет ок?

2020-06-02 21:37 UTC, ASVVlasov commented on frontend/src/redux/auth/operations.js
> +   console.log(authInfo)
убери консоль

2020-06-02 21:37 UTC, ASVVlasov commented on frontend/src/redux/auth/operations.js
> +      history.push('/profile/travels')
мы же с тобой на созвоне определились что тут в фетче возращать результат запроса а в компоненте его уже редиректить

2020-06-02 21:37 UTC, ASVVlasov commented on frontend/src/redux/auth/actions.js
> +})
создал экшн который нигде не используется, зачем?

2020-06-03 13:15 UTC, LenaMaltseva requested changes

2020-06-03 13:15 UTC, LenaMaltseva commented on frontend/src/components/Registartion/Registration.jsx
> +         tabs[index].emailLabel = index ? 'Введите почту' : ''
У тебя нормально ошибки валидации отображаются? У меня каша из надписей в два ряда и в два слоя, а на странице входа все это вообще сдвигает собой инпуты
И обсуждали их в хинтЛейбл отображать..

2020-06-03 13:15 UTC, LenaMaltseva commented on frontend/src/pages/HomePage/HomePage.jsx
> +               <LogoIcon className={styles['icon']} />
Лого это лого, зачем тут icon?

2020-06-03 13:15 UTC, LenaMaltseva commented on frontend/src/pages/HomePage/HomePage.module.scss
> +    @include Icon(170px);
не надо из логотипа делать иконку,
и после этого можно убрать импорт миксинов

2020-06-03 13:15 UTC, LenaMaltseva commented on frontend/src/assets/images/slide3.svg
> +<svg width="532" height="385" viewBox="0 0 532 385" fill="none" xmlns="http://www.w3.org/2000/svg">
выпили из ассетов загруженные туда ранее пнг, раз используешь свои файлы

2020-06-03 13:15 UTC, LenaMaltseva commented on frontend/src/assets/images/icons/left.svg
> +<svg width="23" height="40" viewBox="0 0 23 40" fill="none" xmlns="http://www.w3.org/2000/svg">
в слайдере есть родные стрелки, которые ничем не отличаются от макета, со своей стороны не вижу смысла наворачивать свои, но тут как сам посчитаешь..

2020-06-03 13:15 UTC, LenaMaltseva commented on frontend/src/components/Registartion/Registration.jsx
> +      let reg = new RegExp('[^@]+@[^@]+.[^@]+')
не соглашусь насчет критичности
и const)

2020-06-03 13:15 UTC, LenaMaltseva commented on frontend/src/components/Registartion/Registration.jsx
> +      const index = this.state.tabs.findIndex(
this.state.tabs строкой выше вынесено в переменную tabs

2020-06-03 13:15 UTC, LenaMaltseva commented on frontend/src/components/Registartion/Registration.jsx
> +         this.setState({ tabs: tabs })
здесь и ниже можно this.setState({ tabs })

2020-06-03 13:15 UTC, LenaMaltseva commented on frontend/src/components/Registartion/Registration.jsx
> +            <Button onClick={this.login} text={tab.btnText} ml={0} />
ml (margin-left) это необязательное свойство, зачем передавать 0?

2020-06-03 13:15 UTC, LenaMaltseva commented on frontend/src/components/Slider/Slider.jsx
> +import styles from './Slider.module.scss'
двойной импорт?

2020-06-03 13:15 UTC, LenaMaltseva commented on frontend/src/components/Slider/Slider.jsx
> +         //  },
выпилить?

2020-06-03 13:15 UTC, LenaMaltseva commented on frontend/src/components/Slider/Slider.jsx
> +                  <p className={styles['text-main']}>новыми впечатлениями</p>
`<br/>`?

2020-06-03 13:15 UTC, LenaMaltseva commented on frontend/src/redux/auth/operations.js
> +      history.push('/profile/travels')
есть fetchRequest в /redux/fetch/operations

2020-06-03 13:15 UTC, LenaMaltseva commented on frontend/src/pages/HomePage/HomePage.module.scss
> +$width: 1440px;
переменная которая используется в одном месте? зачем?

2020-06-03 16:23 UTC, Konstantin-Buzuev commented on frontend/src/pages/HomePage/HomePage.jsx
> +               <LogoIcon className={styles['icon']} />
+

2020-06-03 16:24 UTC, Konstantin-Buzuev commented on frontend/src/pages/HomePage/HomePage.jsx
> +               <LogoIcon className={styles['icon']} />
+

2020-06-03 16:25 UTC, Konstantin-Buzuev commented on frontend/src/pages/HomePage/HomePage.module.scss
> +    @include Icon(170px);
+

2020-06-03 16:26 UTC, Konstantin-Buzuev commented on frontend/src/assets/images/slide3.svg
> +<svg width="532" height="385" viewBox="0 0 532 385" fill="none" xmlns="http://www.w3.org/2000/svg">
+

2020-06-03 16:27 UTC, Konstantin-Buzuev commented on frontend/src/pages/HomePage/HomePage.module.scss
> +$width: 1440px;
+

2020-06-03 16:28 UTC, Konstantin-Buzuev commented on frontend/src/components/Registartion/Registration.jsx
> +   passwordIsValid = (value) => (value.length >= 6 ? true : false)
+

2020-06-03 19:08 UTC, Konstantin-Buzuev commented on frontend/src/components/Registartion/Registration.jsx
> +      let reg = new RegExp('[^@]+@[^@]+.[^@]+')
+

2020-06-03 19:20 UTC, Konstantin-Buzuev commented on frontend/src/components/Registartion/Registration.jsx
> +      authInfo.rememberMe = this.state.rememberMe
+

2020-06-03 19:24 UTC, Konstantin-Buzuev commented on frontend/src/components/Registartion/Registration.jsx
> +      let tabs = this.state.tabs
+

2020-06-03 21:24 UTC, Konstantin-Buzuev commented on frontend/src/components/Registartion/Registration.jsx
> +         tabs[index].emailLabel = index ? 'Введите почту' : ''
index поправил, по input-ам - надо обсудить.

2020-06-03 21:27 UTC, Konstantin-Buzuev commented on frontend/src/redux/auth/actions.js
> +})
+

2020-06-03 22:00 UTC, Konstantin-Buzuev commented on frontend/src/pages/HomePage/HomePage.jsx
> +               <LogoIcon className={styles['icon']} />
+

2020-06-03 22:00 UTC, Konstantin-Buzuev commented on frontend/src/redux/auth/actions.js
> +})
+

2020-06-03 22:06 UTC, Konstantin-Buzuev commented on frontend/src/redux/auth/operations.js
> +   console.log(authInfo)
+

2020-06-03 22:06 UTC, Konstantin-Buzuev commented on frontend/src/redux/auth/operations.js
> +      throw new Error(res.statusText)
+

2020-06-03 22:06 UTC, Konstantin-Buzuev commented on frontend/src/pages/HomePage/HomePage.jsx
> +               <LogoIcon className={styles['icon']} />
+

2020-06-03 23:21 UTC, Konstantin-Buzuev commented on frontend/src/redux/auth/operations.js
> +      history.push('/profile/travels')
+

2020-06-03 23:21 UTC, Konstantin-Buzuev commented on frontend/src/assets/images/icons/left.svg
> +<svg width="23" height="40" viewBox="0 0 23 40" fill="none" xmlns="http://www.w3.org/2000/svg">
+

2020-06-03 23:24 UTC, Konstantin-Buzuev commented on frontend/src/components/Slider/Slider.jsx
> +import styles from './Slider.module.scss'
+

2020-06-03 23:24 UTC, Konstantin-Buzuev commented on frontend/src/components/Slider/Slider.jsx
> +         //  },
+

2020-06-03 23:24 UTC, Konstantin-Buzuev commented on frontend/src/components/Slider/Slider.jsx
> +                  <p className={styles['text-main']}>новыми впечатлениями</p>
-

2020-06-04 17:15 UTC, Konstantin-Buzuev commented on frontend/src/pages/HomePage/HomePage.jsx
> +               <LogoIcon className={styles['icon']} />
Исправил.

2020-06-04 17:15 UTC, Konstantin-Buzuev commented on frontend/src/pages/HomePage/HomePage.module.scss
> +    @include Icon(170px);
Исправил.

2020-06-04 17:15 UTC, Konstantin-Buzuev commented on frontend/src/components/Slider/Slider.jsx
> +import styles from './Slider.module.scss'
Исправил.

2020-06-04 17:15 UTC, Konstantin-Buzuev commented on frontend/src/components/Slider/Slider.jsx
> +         //  },
Выпилил.

2020-06-04 17:16 UTC, Konstantin-Buzuev commented on frontend/src/components/Slider/Slider.jsx
> +                  <p className={styles['text-main']}>новыми впечатлениями</p>
Оставил <p>. Или это критично?

2020-06-04 17:16 UTC, Konstantin-Buzuev commented on frontend/src/pages/HomePage/HomePage.module.scss
> +$width: 1440px;
Исправил.

2020-06-04 17:16 UTC, Konstantin-Buzuev commented on frontend/src/components/Registartion/Registration.jsx
> +   passwordIsValid = (value) => (value.length >= 6 ? true : false)
Исправил.

2020-06-04 17:16 UTC, Konstantin-Buzuev commented on frontend/src/components/Registartion/Registration.jsx
> +      let reg = new RegExp('[^@]+@[^@]+.[^@]+')
RegExp исправил.

2020-06-04 17:17 UTC, Konstantin-Buzuev commented on frontend/src/components/Registartion/Registration.jsx
> +      authInfo.rememberMe = this.state.rememberMe
Исправил.

2020-06-04 17:17 UTC, Konstantin-Buzuev commented on frontend/src/components/Registartion/Registration.jsx
> +      let tabs = this.state.tabs
Исправил.

2020-06-04 17:18 UTC, Konstantin-Buzuev commented on frontend/src/pages/HomePage/HomePage.jsx
> +               <LogoIcon className={styles['icon']} />
Исправил.

2020-06-04 17:18 UTC, Konstantin-Buzuev commented on frontend/src/redux/auth/operations.js
> +      throw new Error(res.statusText)
Убрал

2020-06-04 17:18 UTC, Konstantin-Buzuev commented on frontend/src/redux/auth/operations.js
> +   console.log(authInfo)
Убрал

2020-06-04 17:18 UTC, Konstantin-Buzuev commented on frontend/src/redux/auth/operations.js
> +      history.push('/profile/travels')
Исправил

2020-06-04 17:18 UTC, Konstantin-Buzuev commented on frontend/src/redux/auth/actions.js
> +})
Исправил

2020-06-04 17:20 UTC, Konstantin-Buzuev commented on frontend/src/components/Registartion/Registration.jsx
> +      const index = this.state.tabs.findIndex(
Исправил

2020-06-04 17:21 UTC, Konstantin-Buzuev commented on frontend/src/components/Registartion/Registration.jsx
> +            <Button onClick={this.login} text={tab.btnText} ml={0} />
Исправил

2020-06-04 17:22 UTC, Konstantin-Buzuev commented on frontend/src/components/Registartion/Registration.jsx
> +         this.setState({ tabs: tabs })
Поправил

2020-06-04 17:24 UTC, Konstantin-Buzuev commented on frontend/src/components/Registartion/Registration.jsx
> +      this.props.authorization(authInfo, '/' + this.props.match.params.tab)
Исправил с помощью then

2020-06-04 17:24 UTC, Konstantin-Buzuev commented on frontend/src/components/Registartion/Registration.jsx
> +            activeClassName={styles['tabs-link_active']}
Исправил

2020-06-04 17:25 UTC, Konstantin-Buzuev commented on frontend/src/components/Registartion/Registration.jsx
> +            <nav className={styles['tabs']} children={this.mapTabsToRender()} />
Для единообразия оставил так. Это критично?

2020-06-04 17:25 UTC, Konstantin-Buzuev commented on frontend/src/components/Registartion/Registration.module.scss
> +}
Исправил

2020-06-04 17:25 UTC, Konstantin-Buzuev commented on frontend/src/components/Slider/Slider.module.scss
> +    top: 218px;
Исправил

2020-06-04 17:37 UTC, ASVVlasov requested changes

2020-06-04 17:37 UTC, ASVVlasov commented on frontend/src/components/Registartion/Registration.jsx
> +      return res
return value.length > 5
тут больше ничего не нужно, и опять let, забудь это слово)

2020-06-04 17:37 UTC, ASVVlasov commented on frontend/src/components/Registartion/Registration.jsx
> +            <nav className={styles['tabs']} children={this.mapTabsToRender()} />{' '}
у тебя везде в конце тега {' '} что это? и зачем? стили везде исправь без квадратный скобок, и если у тебя tabs это элемент form, то должно быть form__tabs, тоже пройдись везде и подправь бэм

2020-06-04 17:37 UTC, ASVVlasov commented on frontend/src/components/Registartion/Registration.module.scss
> +}
если кнопка - элемент блока form - &__button, &__tabs, в компонентах будет styles.form__button, styles.form__tabs

2020-06-04 17:37 UTC, ASVVlasov commented on frontend/src/components/Slider/Slider.jsx
> +                     новыми впечатлениями
убери везде квадратные скобки

2020-06-04 17:37 UTC, ASVVlasov commented on frontend/src/pages/HomePage/HomePage.jsx
> +               <Logo className={styles['page__logo']} />
квадратные скобки

2020-06-04 18:24 UTC, LenaMaltseva commented on frontend/src/components/Slider/Slider.jsx
> +                  <p className={styles['text-main']}>новыми впечатлениями</p>
Нет, просто для чего тут два параграфа с одинаковым классом, если строки можно разделять тегом.

2020-06-04 18:27 UTC, LenaMaltseva requested changes

2020-06-04 18:27 UTC, LenaMaltseva commented on frontend/src/components/Slider/Slider.jsx
> +                  </p>
Во всех надписях на слайдере нужно перечислять классы - сейчас миксин с определением шрифта к ним не относится

2020-06-04 18:49 UTC, LenaMaltseva submitted a review, later dismissed

2020-06-04 19:10 UTC, ASVVlasov approved these changes

2020-06-04 19:10 UTC, merged